#!/bin/bash
#----------------------
#This is a script that will automatically configure your Arch for audio production.
#-----------------------
#Exit if the script fails
#This still on beta so it might change overtime!

notify () {

	echo "--------------------------------------------"
	echo "Audio Linux Production all in one script"
	echo "--------------------------------------------"
}


###Data variables (this will be used for the logic of the script)
###This will be used later

###This will clear the terminal
clear

###User Agreement

COLUMNS=$(tput cols)
title="!!WARNING, MUST READ BEFORE DOING ANYTHING!!"

printf '\033[0;31m'
printf "%*s\n" $(((${#title}+$COLUMNS)/2))  "$title"
printf '\033[0m'
printf "\n"
printf "This script is a beta version, expect bugs and crashes.\nI dont guarantee that this will work on your pc\nUnder no circumstances that im realiable to any damage or data loss\nYou choose to download this script under your own will\nTherefore you must understand the consequences of running the script.\n"
printf "\n"

read -p "Please type 'I Understand'(Exactly like this) to continue: " ANS
